[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "mast3r"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
]
dependencies = []


[tool.setuptools.packages.find]
include = ["mast3r"]
